"""add narrative_description to story_characters

Revision ID: 1abef5ecd216
Revises: 3ba03aba15bb
Create Date: 2026-01-30 20:24:30.668126

"""

from alembic import op
import sqlalchemy as sa


revision = '1abef5ecd216'
down_revision = '3ba03aba15bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_characters', sa.Column('narrative_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_characters', 'narrative_description')
    # ### end Alembic commands ###
