"""add_audit_fields_to_stories

Revision ID: 4cb9fcf85a67
Revises: 20260129_0008
Create Date: 2026-01-29 20:38:22.572085

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql




revision = '4cb9fcf85a67'
down_revision = '20260129_0009'


branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('style_presets',
    sa.Column('preset_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('style_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('style_config', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['style_presets.preset_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('preset_id')
    )
    op.add_column('artifacts', sa.Column('created_by', sa.String(length=64), nullable=True))
    op.add_column('artifacts', sa.Column('updated_by', sa.String(length=64), nullable=True))
    op.alter_column('artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_artifacts_scene_type_version'), table_name='artifacts')
    op.alter_column('character_reference_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('character_variant_suggestions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_variant_suggestions_story_character'), table_name='character_variant_suggestions')
    op.alter_column('character_variants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_character_variants_story_character'), table_name='character_variants')
    op.alter_column('characters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dialogue_layers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('environment_anchors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_episode_assets_episode_id'), table_name='episode_assets')
    op.drop_index(op.f('ix_episode_scenes_episode_id'), table_name='episode_scenes')
    op.drop_index(op.f('ix_episode_scenes_scene_id'), table_name='episode_scenes')
    op.alter_column('episodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_exports_episode_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_scene_id'), table_name='exports')
    op.drop_constraint(op.f('fk_exports_episode_id'), 'exports', type_='foreignkey')
    op.alter_column('images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('layers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_layers_scene_id'), table_name='layers')
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('scenes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('scenes', sa.Column('created_by', sa.String(length=64), nullable=True))
    op.add_column('scenes', sa.Column('updated_by', sa.String(length=64), nullable=True))
    op.alter_column('scenes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_scenes_environment_id'), 'scenes', type_='foreignkey')
    op.add_column('stories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('stories', sa.Column('created_by', sa.String(length=64), nullable=True))
    op.add_column('stories', sa.Column('updated_by', sa.String(length=64), nullable=True))
    op.alter_column('stories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('story_characters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story_characters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('stories', 'updated_by')
    op.drop_column('stories', 'created_by')
    op.drop_column('stories', 'updated_at')
    op.create_foreign_key(op.f('fk_scenes_environment_id'), 'scenes', 'environment_anchors', ['environment_id'], ['environment_id'])
    op.alter_column('scenes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('scenes', 'updated_by')
    op.drop_column('scenes', 'created_by')
    op.drop_column('scenes', 'updated_at')
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_layers_scene_id'), 'layers', ['scene_id'], unique=False)
    op.alter_column('layers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(op.f('fk_exports_episode_id'), 'exports', 'episodes', ['episode_id'], ['episode_id'])
    op.create_index(op.f('ix_exports_scene_id'), 'exports', ['scene_id'], unique=False)
    op.create_index(op.f('ix_exports_episode_id'), 'exports', ['episode_id'], unique=False)
    op.alter_column('exports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('episodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_episode_scenes_scene_id'), 'episode_scenes', ['scene_id'], unique=False)
    op.create_index(op.f('ix_episode_scenes_episode_id'), 'episode_scenes', ['episode_id'], unique=False)
    op.create_index(op.f('ix_episode_assets_episode_id'), 'episode_assets', ['episode_id'], unique=False)
    op.alter_column('environment_anchors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dialogue_layers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('characters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_character_variants_story_character'), 'character_variants', ['story_id', 'character_id'], unique=False)
    op.alter_column('character_variants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_variant_suggestions_story_character'), 'character_variant_suggestions', ['story_id', 'character_id'], unique=False)
    op.alter_column('character_variant_suggestions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('character_reference_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_artifacts_scene_type_version'), 'artifacts', ['scene_id', 'type', 'version'], unique=True)
    op.alter_column('artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('artifacts', 'updated_by')
    op.drop_column('artifacts', 'created_by')
    op.drop_table('style_presets')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
