"""Add missing columns to Character model

Revision ID: d36c3bc44c8c
Revises: 4cb9fcf85a67
Create Date: 2026-01-29 23:00:29.306595

"""

from alembic import op
import sqlalchemy as sa


revision = 'd36c3bc44c8c'
down_revision = '4cb9fcf85a67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('generation_prompt', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('is_library_saved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'is_library_saved')
    op.drop_column('characters', 'generation_prompt')
    # ### end Alembic commands ###
