import re

_NAME_STOPWORDS = {
    "The",
    "A",
    "An",
    "He",
    "She",
    "They",
    "It",
    "His",
    "Her",
    "Their",
    "I",
    "We",
    "You",
    "My",
    "Our",
    "Your",
    "Me",
    "Us",
    "Mine",
    "Ours",
    "Yours",
    "This",
    "That",
    "These",
    "Those",
    "And",
    "But",
    "Or",
    "So",
    "Because",
    "When",
    "While",
    "After",
    "Before",
    "If",
    "Then",
    "As",
    "To",
    "In",
    "On",
    "At",
    "For",
    "With",
    "From",
    "By",
    "Of",
    "Into",
    "Over",
    "Under",
    "Around",
    "Is",
    "Are",
    "Was",
    "Were",
    "Be",
    "Being",
    "Been",
    "Do",
    "Does",
    "Did",
    "Can",
    "Could",
    "Should",
    "Would",
    "Will",
    "Shall",
    "May",
    "Might",
    "Must",
    "Man",
    "Woman",
    "Boy",
    "Girl",
    "Child",
    "Children",
    "People",
    "Person",
    "Someone",
    "Something",
    "Nothing",
    "Everything",
    "Anyone",
    "Everyone",
    "Nobody",
    "Somebody",
    "Everybody",
    "None",
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight",
    "Nine",
    "Ten",
    "First",
    "Second",
    "Third",
    "Today",
    "Yesterday",
    "Tomorrow",
    "Morning",
    "Afternoon",
    "Evening",
    "Night",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
    "City",
    "Town",
    "Village",
    "Street",
    "Road",
    "Lane",
    "House",
    "Home",
    "Room",
    "Office",
    "Cafe",
    "School",
    "College",
    "University",
    "Station",
    "Hospital",
    "Park",
    "River",
    "Sea",
    "Mountain",
    "Forest",
    "Market",
    "Temple",
    "Church",
    "Temple",
    "Roommate",
    "Classmate",
    "Friend",
    "Friends",
    "Boss",
    "Teacher",
    "Dad",
    "Mom",
    "Mother",
    "Father",
    "Brother",
    "Sister",
    "Siblings",
    "Grandma",
    "Grandpa",
    "Everyone",
    "Some",
    "Many",
    "Few",
    "Most",
    "All",
    "Each",
    "Every",
    "Several",
    "Various",
    "Any",
    "Other",
    "Another",
    "Else",
    "New",
    "Old",
    "Young",
    "Little",
    "Big",
    "Small",
    "Large",
    "Good",
    "Bad",
    "Best",
    "Worst",
    "Great",
    "Nice",
    "Mean",
    "Kind",
    "Happy",
    "Sad",
    "Angry",
    "Smile",
    "Smiles",
    "Smiled",
    "Okay",
    "Ok",
    "Yes",
    "No",
}


def _split_sentences(text: str) -> list[str]:
    parts = re.split(r"(?<=[.!?])\s+", text.strip())
    return [p.strip() for p in parts if p.strip()]


def _extract_names(text: str, excluded: set[str] | None = None) -> list[str]:
    excluded = excluded or set()
    candidates = re.findall(r"\b[A-Z][a-z]+(?:\s+[A-Z][a-z]+)?\b", text or "")
    names: list[str] = []
    for candidate in candidates:
        if candidate in _NAME_STOPWORDS:
            continue
        if candidate in excluded:
            continue
        if candidate not in names:
            names.append(candidate)
    return names


def _extract_metadata_names(text: str) -> set[str]:
    excluded: set[str] = set()
    for line in (text or "").splitlines()[:20]:
        stripped = line.strip()
        lower = stripped.lower()
        if ":" in line:
            label, rest = line.split(":", 1)
            label_key = label.strip().lower()
            if label_key in {"title", "episode", "story", "genre", "style"}:
                for candidate in re.findall(r"\b[A-Z][a-z]+(?:\s+[A-Z][a-z]+)?\b", rest):
                    excluded.add(candidate)
        elif any(lower.startswith(prefix) for prefix in ("title", "episode", "story", "genre", "style")):
            for candidate in re.findall(r"\b[A-Z][a-z]+(?:\s+[A-Z][a-z]+)?\b", stripped):
                excluded.add(candidate)
    return excluded


def _summarize_text(text: str, max_words: int = 32) -> str:
    words = re.findall(r"\w+", text)
    if not words:
        return ""
    return " ".join(words[:max_words])
